name: million
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
#  connectivity: ^3.0.6
  connectivity_plus: ^4.0.2
  shimmer_animation: ^2.1.0+1
  flutter_neumorphic: ^3.2.0
#  neumorphic_container: ^0.0.1+2
  animated_text_kit: ^4.2.2
  card_swiper: ^2.0.3
  chewie: ^1.3.1
  video_player: ^2.3.0
  image_picker: ^0.8.6
  flutter_picker: ^2.0.5
  wheel_chooser: ^1.0.0
  otp_text_field: ^1.1.3
  focus_detector: ^2.0.1
  motion_toast: ^2.3.2
#  pinch_zoom: ^1.0.0
  pinch_zoom_release_unzoom: ^1.0.1
  smooth_page_indicator: ^1.0.1
  firebase_messaging: ^14.1.4
  firebase_auth: ^4.4.0
  firebase_core: ^2.7.1
  cloud_firestore: ^4.8.2
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.17.0
  octo_image: ^1.0.1
  firebase_storage: ^11.2.4
  file_picker: ^5.0.0
  emoji_picker_flutter: ^1.6.1
  agora_rtc_engine: ^5.3.1
  just_audio: ^0.9.34
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  image_cropper: ^3.0.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
#    - assets/fonts/
    - assets/sounds/
#    - assets/videos/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Regular.ttf
          weight: 400
        - asset: assets/font/DMSans-Medium.ttf
          weight: 500
        - asset: assets/font/DMSans-Bold.ttf
          weight: 700